### ISSUE TITLE
No corvage date when run test

### ISSUE THREAD

**Issue by iyw-top** [emyann/typescript-webpack-starter#15]
When i run the test "npm test" karma run the unit tests fine, but there are no coverage data in 
/tests/build/reports/coverage/report-html/index.html

**npm test**
my-typescript-lib@0.0.1 test d:\Data\repository\webpack\my-typescript-lib
karma start
[at-loader] Using typescript@2.7.1 from typescript and "tsconfig.json" from d:\Data\repository\webpack\my-typescript-lib/tsconfig.json.
[at-loader] Checking started in a separate process...
[at-loader] Ok, 0.575 sec.
06 02 2018 10:59:49.052:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
06 02 2018 10:59:49.052:INFO [launcher]: Launching browser Chrome with unlimited concurrency
06 02 2018 10:59:49.092:INFO [launcher]: Starting browser Chrome
06 02 2018 10:59:51.108:INFO [Chrome 63.0.3239 (Windows 7.0.0)]: Connected on socket TFAtGZAirSZM__kwAAAA with id 41780039
LOG: 'HELLO'
LOG LOG: 'HELLO'

  Hello test
    V Create hello object

  TypeScript WebPack Starter Tests
    V A good way to start building an awesome lib is by doing Unit Tests ??

Chrome 63.0.3239 (Windows 7.0.0): Executed 2 of 2 SUCCESS (0.041 secs / 0 secs)
TOTAL: 2 SUCCESS

![image](https://user-images.githubusercontent.com/29246397/35853430-c06ad884-0b2d-11e8-87fc-6f35b7f46963.png)

**Comment by emyann** [comment]
@iyw-top Thanks for your feedback 👌🏽This has been fixed in the referenced PR

**Comment by iyw-top** [comment]
thanks for the quick fix
