### ISSUE TITLE
No .gitignore in generated project

### ISSUE THREAD

**Issue by rhys-vdw** [emyann/typescript-webpack-starter#9]
Documetation suggests a `.gitignore` would be in the generated directory, which would be cool. However there doesn't appear to be one in the [template](https://github.com/emyann/typescript-webpack-starter/tree/master/packages/cli/template) directory or in my generated project.

**Comment by emyann** [comment]
Thank you @rhys-vdw for the catch up! 🙏🏽  It is now fixed in the last published version https://www.npmjs.com/package/create-ts-lib
